<?xml version="1.0"?>
<!DOCTYPE issues [
<!ELEMENT issues (issue*)>
<!ATTLIST issues burpVersion CDATA "">
<!ATTLIST issues exportTime CDATA "">
<!ELEMENT issue (serialNumber, type, name, host, path, location, severity, confidence, issueBackground?, remediationBackground?, issueDetail?, issueDetailItems?, remediationDetail?, requestresponse*)>
<!ELEMENT serialNumber (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ATTLIST host ip CDATA "">
<!ELEMENT path (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT severity (#PCDATA)>
<!ELEMENT confidence (#PCDATA)>
<!ELEMENT issueBackground (#PCDATA)>
<!ELEMENT remediationBackground (#PCDATA)>
<!ELEMENT issueDetail (#PCDATA)>
<!ELEMENT issueDetailItems (issueDetailItem*)>
<!ELEMENT issueDetailItem (#PCDATA)>
<!ELEMENT remediationDetail (#PCDATA)>
<!ELEMENT requestresponse (request?, response?, responseRedirected?)>
<!ELEMENT request (#PCDATA)>
<!ATTLIST request method CDATA "">
<!ATTLIST request base64 (true|false) "false">
<!ELEMENT response (#PCDATA)>
<!ATTLIST response base64 (true|false) "false">
<!ELEMENT responseRedirected (#PCDATA)>
]>
<issues burpVersion="1.5.21" exportTime="Wed Feb 05 09:40:28 CST 2014">
  <issue>
    <serialNumber>1236521271099772928</serialNumber>
    <type>5244416</type>
    <name>Cookie without HttpOnly flag set</name>
    <host ip="23.194.34.24">http://pt200204.unica.com</host>
    <path><![CDATA[/ntpagetag.gif]]></path>
    <location><![CDATA[/ntpagetag.gif]]></location>
    <severity>Information</severity>
    <confidence>Certain</confidence>
    <issueBackground><![CDATA[If the HttpOnly attribute is set on a cookie, then the cookie's value cannot be read or set by client-side JavaScript. This measure can prevent certain client-side attacks, such as cross-site scripting, from trivially capturing the cookie's value via an injected script.]]></issueBackground>
    <remediationBackground><![CDATA[There is usually no good reason not to set the HttpOnly flag on all cookies. Unless you specifically require legitimate client-side scripts within your application to read or set a cookie's value, you should set the HttpOnly flag by including this attribute within the relevant Set-cookie directive.<br><br>You should be aware that the restrictions imposed by the HttpOnly flag can potentially be circumvented in some circumstances, and that numerous other serious attacks can be delivered by client-side script injection, aside from simple cookie stealing.]]></remediationBackground>
    <issueDetail><![CDATA[The following cookie was issued by the application and does not have the HttpOnly flag set:<ul><li>UnicaID=10.39.18.251-1391614605177306; path=/; expires=Sat, 09-Feb-19 15:36:45 GMT</li></ul>The cookie does not appear to contain a session token, which may reduce the risk associated with this issue. You should review the contents of the cookie to determine its function.]]></issueDetail>
    <issueDetailItems>
      <issueDetailItem><![CDATA[UnicaID=10.39.18.251-1391614605177306; path=/; expires=Sat, 09-Feb-19 15:36:45 GMT]]></issueDetailItem>
    </issueDetailItems>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC9udHBhZ2V0YWcuZ2lmP2pzPTEmdHM9MTM5MTYxNDYwNDk0Mi4yNjImbGM9aHR0cCUzQSUyRiUyRnd3dy5pYm0uY29tJTJGdXMlMkZlbiUyRiZycz0xOTIweDEwODAmY2Q9MjQmbG49ZW4mdHo9R01UJTIwLTA2JTNBMDAmanY9MSZjaz1VbmljYU5JT0RJRCUzRDlWMkR4ajhHTFVMLVlmQWxEMzUmZXRzPTEzOTE2MTQ2MDUxMTQuOTMzJmlibS5pbnB1dGNvdW50cnk9VVMmZXY9cGVycyUyMGFjdGlvbiZpYm1Fdk5hbWU9aWJtaG9tZXBlcnMmaWJtRXZHcm91cD1ub25lJmlibUV2U2VjdGlvbj1zZXJ2aWNlJmlibUV2VGFyZ2V0PXNlcnZpY2UlMjBjYWxsZWQmaWJtRXZNb2R1bGU9bm9uZSZpYm1FdkFjdGlvbj1ub25lIEhUVFAvMS4xDQpIb3N0OiBwdDIwMDIwNC51bmljYS5jb20NClVzZXItQWdlbnQ6IE1vemlsbGEvNS4wIChYMTE7IFVidW50dTsgTGludXggeDg2XzY0OyBydjoyNi4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzI2LjANCkFjY2VwdDogaW1hZ2UvcG5nLGltYWdlLyo7cT0wLjgsKi8qO3E9MC41DQpBY2NlcHQtTGFuZ3VhZ2U6IGVuLVVTLGVuO3E9MC41DQpBY2NlcHQtRW5jb2Rpbmc6IGd6aXAsIGRlZmxhdGUNClJlZmVyZXI6IGh0dHA6Ly93d3cuaWJtLmNvbS91cy9lbi8NCkNvbm5lY3Rpb246IGtlZXAtYWxpdmUNCg0K]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpTZXJ2ZXI6IEFwYWNoZQ0KTGFzdC1Nb2RpZmllZDogVHVlLCAzMCBKYW4gMjAwNyAyMTo1ODo0OCBHTVQNCkVUYWc6ICIyZmQ4ZWQtNTUtNDI4NDkxOTNkMTYwMCINCkFjY2VwdC1SYW5nZXM6IGJ5dGVzDQpDb250ZW50LUxlbmd0aDogODUNClAzUDogQ1A9Ik5PSSBEU1AgQ09SIFBTQSBBRE1hIERFVmEgT1VSIElORCBPVEMiDQpDb250ZW50LVR5cGU6IGltYWdlL2dpZg0KRXhwaXJlczogV2VkLCAwNSBGZWIgMjAxNCAxNTozNjo0NSBHTVQNCkNhY2hlLUNvbnRyb2w6IG1heC1hZ2U9MCwgbm8tY2FjaGUsIG5vLXN0b3JlDQpQcmFnbWE6IG5vLWNhY2hlDQpEYXRlOiBXZWQsIDA1IEZlYiAyMDE0IDE1OjM2OjQ1IEdNVA0KQ29ubmVjdGlvbjoga2VlcC1hbGl2ZQ0KU2V0LUNvb2tpZTogVW5pY2FJRD0xMC4zOS4xOC4yNTEtMTM5MTYxNDYwNTE3NzMwNjsgcGF0aD0vOyBleHBpcmVzPVNhdCwgMDktRmViLTE5IDE1OjM2OjQ1IEdNVA0KDQpHSUY4OWEBAAEAsw0AAAAAgAAAAIAAgIAAAACAgACAAICAgICAwMDA/wAAAP8A//8AAAD//wD/AP//////IfkEAQAADQAsAAAAAAEAAQBABAKwRQA7]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>3358578457710747648</serialNumber>
    <type>5244160</type>
    <name>Cross-domain script include</name>
    <host ip="23.194.35.152">http://www.ibm.com</host>
    <path><![CDATA[/common/stats/stats.js]]></path>
    <location><![CDATA[/common/stats/stats.js]]></location>
    <severity>Information</severity>
    <confidence>Certain</confidence>
    <issueBackground><![CDATA[When an application includes a script from an external domain, this script is executed by the browser within the security context of the invoking application. The script can therefore do anything that the application's own scripts can do, such as accessing application data and performing actions within the context of the current user.<br><br>If you include a script from an external domain, then you are trusting that domain with the data and functionality of your application, and you are trusting the domain's own security to prevent an attacker from modifying the script to perform malicious actions within your application.]]></issueBackground>
    <remediationBackground><![CDATA[Scripts should not be included from untrusted domains. If you have a requirement which a third-party script appears to fulfill, then you should ideally copy the contents of that script onto your own domain and include it from there. If that is not possible (e.g. for licensing reasons) then you should consider reimplementing the script's functionality within your own code.]]></remediationBackground>
    <issueDetail><![CDATA[The response dynamically includes the following script from another domain:<ul><li>http://consent.truste.com/notice?domain=ibm.com&amp;c=ibm-truste</li></ul>]]></issueDetail>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC9jb21tb24vc3RhdHMvc3RhdHMuanMgSFRUUC8xLjENCkhvc3Q6IHd3dy5pYm0uY29tDQpVc2VyLUFnZW50OiBNb3ppbGxhLzUuMCAoWDExOyBVYnVudHU7IExpbnV4IHg4Nl82NDsgcnY6MjYuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC8yNi4wDQpBY2NlcHQ6ICovKg0KQWNjZXB0LUxhbmd1YWdlOiBlbi1VUyxlbjtxPTAuNQ0KQWNjZXB0LUVuY29kaW5nOiBnemlwLCBkZWZsYXRlDQpSZWZlcmVyOiBodHRwOi8vd3d3LmlibS5jb20vdXMvZW4vDQpDb25uZWN0aW9uOiBrZWVwLWFsaXZlDQoNCg==]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpMYXN0LU1vZGlmaWVkOiBUdWUsIDEyIE5vdiAyMDEzIDEwOjIyOjI5IEdNVA0KRVRhZzogIjRkM2YtNGVhZjgzOWM3NjM0MCINCkFjY2VwdC1SYW5nZXM6IGJ5dGVzDQpDdGVvbm50LUxlbmd0aDogMTk3NzUNCmVwS2UtQWxpdmU6IHRpbWVvdXQ9MTAsIG1heD04OQ0KQ29udGVudC1UeXBlOiBhcHBsaWNhdGlvbi94LWphdmFzY3JpcHQNCkNvbnRlbnQtTGVuZ3RoOiAxOTc3NQ0KQ2FjaGUtQ29udHJvbDogbWF4LWFnZT04OTcNCkV4cGlyZXM6IFdlZCwgMDUgRmViIDIwMTQgMTU6NTE6MzkgR01UDQpEYXRlOiBXZWQsIDA1IEZlYiAyMDE0IDE1OjM2OjQyIEdNVA0KQ29ubmVjdGlvbjoga2VlcC1hbGl2ZQ0KVmFyeTogQWNjZXB0LUVuY29kaW5nDQoNCi8qIQogKiAkSWQ6IHN0YXRzLmpzLHYgMS4xNTEgMjAxMy8xMS8xMiAxMDoyMjoyOSBrb2xsYXJpayBFeHAgJAogKiBDb3B5cmlnaHQgKGMpIDIwMDkgSUJNIENvcnBvcmF0aW9uCiAqIE93bmVyOiBDb3Jwb3JhdGUgV2VibWFzdGVyIChOVVNfTl9OSVdXVykKICovCnZhciBOVFBUX05PSU5JVElBTFRBRz10cnVlO3ZhciBOVFBUX0lNR1NSQz0iLy9wdDIwMDIwNC51bmljYS5jb20vbnRwYWdldGFnLmdpZiI7dmFyIE5UUFRfRkxEUz1uZXcgT2JqZWN0KCk7TlRQVF9GTERTLmxjPXRydWU7TlRQVF9GTERTLnJmPXRydWU7TlRQVF9GTERTLnJzPXRydWU7TlRQVF9GTERTLmNkPXRydWU7TlRQVF9GTERTLmxuPXRydWU7TlRQVF9GTERTLnR6PXRydWU7TlRQVF9GTERTLmp2PXRydWU7TlRQVF9GTERTLmNrPXRydWU7dmFyIE5UUFRfTUFYVEFHV0FJVD0xO3ZhciBOVFBUX0hUVFBTSU1HU1JDPSIvL3B0MjAwMjA0LnVuaWNhLmNvbS9udHBhZ2V0YWcuZ2lmIjt2YXIgTlRQVF9HTEJMUkVGVE9QPWZhbHNlOwp2YXIgTlRQVF9TRVRfSURDT09LSUU9dHJ1ZTt2YXIgTlRQVF9JRENPT0tJRV9OQU1FPSJVbmljYU5JT0RJRCI7dmFyIE5UUFRfSURDT09LSUVfRE9NQUlOPSIuaWJtLmNvbSI7dmFyIE5UUFRfRE9XTkxPQURUWVBFUz0iYnF5LGRvYyxkb3QsZXhlLGZsdixqcGcsbW92LG1wMyxwZGYscHBzLHBwdCxyc3Msc2gsc3dmLHRhcix0eHQsd212LHhscyx4bWwsemlwLGF2aSxlcHMsZ2lmLGx3cCxtYXMsbXA0LHBvdCxwcnoscnRmLHdhdix3bWEsMTIzLG9kdCxvdHQsc3h3LHN0dyxkb2N4LG9kcCxvdHAsc3hpLHN0aSxwcHR4LG9kcyxvdHMsc3hjLHN0Yyx4bHN4Ijt2YXIgTlRQVF9ET01BSU5MSVNUPSIuaWJtLmNvbSwubG90dXMuY29tLC5sb3R1c2xpdmUuY29tLC5jb2dub3MuY29tLC53ZWJkaWFsb2dzLmNvbSwuamF6ei5uZXQsLnNlcnZpY2VtYW5hZ2VtZW50Y2VudGVyLmNvbSI7dmFyIE5UUFRfR0xCTEVYVFJBPSIiO3ZhciBOVFBUX0dMQkxDT09LSUVTPVsiSUJNSVNQIiwiaXdtMXAiXTsKZnVuY3Rpb24gT09PTzAwMChkLGUsYixmKXt2YXIgYT0iIjthPWQrIlx4M2QiK2VzY2FwZShlKSsiXHgzYiI7aWYoZil7YSs9Ilx4MjBceDY0XHg2Zlx4NmRceDYxXHg2OVx4NmVceDNkIitmKyJceDNiIn1pZihiPig3NTI1KzQzNS03OTYwKSl7dmFyIGM9bmV3IERhdGUoKTtjLnNldFRpbWUoYy5nZXRUaW1lKCkrKGIqKDI0NzArMjEwMi0zNTcyKSkpO2ErPSJceDIwXHg2NVx4NzhceDcwXHg2OVx4NzJceDY1XHg3M1x4M2QiK2MudG9HTVRTdHJpbmcoKSsiXHgzYiJ9YSs9Ilx4MjBceDcwXHg2MVx4NzRceDY4XHgzZFx4MmYiO2RvY3VtZW50LmNvb2tpZT1hfWZ1bmN0aW9uIE9PT08wMChiKXt2YXIgYz1iKyJceDNkIjtpZihkb2N1bWVudC5jb29raWUubGVuZ3RoPig1Njc5KzAtNTY3OSkpe3ZhciBkO2Q9ZG9jdW1lbnQuY29va2llLmluZGV4T2YoYyk7aWYoZCE9LSgyNjIrNTc3Mi02MDMzKSl7dmFyIGE7ZCs9Yy5sZW5ndGg7YT1kb2N1bWVudC5jb29raWUuaW5kZXhPZigiXHgzYiIsZCk7CmlmKGE9PS0oNDc2NCs0OTEwLTk2NzMpKXthPWRvY3VtZW50LmNvb2tpZS5sZW5ndGh9cmV0dXJuIHVuZXNjYXBlKGRvY3VtZW50LmNvb2tpZS5zdWJzdHJpbmcoZCxhKSl9ZWxzZXtyZXR1cm4gbnVsbH19fWZ1bmN0aW9uIE8wMDAwME8oYil7dmFyIGE9IiI7Zm9yKE9PMDBPIGluIGIpe2lmKCh0eXBlb2YoYltPTzAwT10pPT0iXHg3M1x4NzRceDcyXHg2OVx4NmVceDY3IikmJihiW09PMDBPXSE9IiIpKXtpZihhIT0iIil7YSs9Ilx4M2IifWErPU9PMDBPKyJceDNkIitiW09PMDBPXX19cmV0dXJuIGF9dmFyIE8wME9PTz1bIlx4NDEiLCJceDQyIiwiXHg0MyIsIlx4NDQiLCJceDQ1IiwiXHg0NiIsIlx4NDciLCJceDQ4IiwiXHg0OSIsIlx4NGEiLCJceDRiIiwiXHg0YyIsIlx4NGQiLCJceDRlIiwiXHg0ZiIsIlx4NTAiLCJceDUxIiwiXHg1MiIsIlx4NTMiLCJceDU0IiwiXHg1NSIsIlx4NTYiLCJceDU3IiwiXHg1OCIsIlx4NTkiLCJceDVhIiwiXHg2MSIsIlx4NjIiLCJceDYzIiwiXHg2NCIsIlx4NjUiLCJceDY2IiwiXHg2NyIsIlx4NjgiLCJceDY5IiwiXHg2YSIsIlx4NmIiLCJceDZjIiwiXHg2ZCIsIlx4NmUiLCJceDZmIiwiXHg3MCIsIlx4NzEiLCJceDcyIiwiXHg3MyIsIlx4NzQiLCJceDc1IiwiXHg3NiIsIlx4NzciLCJceDc4IiwiXHg3OSIsIlx4N2EiLCJceDMwIiwiXHgzMSIsIlx4MzIiLCJceDMzIiwiXHgzNCIsIlx4MzUiLCJceDM2IiwiXHgzNyIsIlx4MzgiLCJceDM5Il07CmZ1bmN0aW9uIE9PT09PTzAoYSl7aWYoYTwoNjUrOTA4NC05MDg3KSl7cmV0dXJuIE8wME9PT1thXX1lbHNle3JldHVybihPT09PT08wKE1hdGguZmxvb3IoYS8oNDQ1MSs2NDQtNTAzMykpKStPMDBPT09bYSUoNzI2MCsxNTcwLTg3NjgpXSl9fWZ1bmN0aW9uIE8wTzAwME8oKXt2YXIgYj0iIjt2YXIgYT1uZXcgRGF0ZSgpO2ZvcihPT08wTzBPPSg1MDQwKzc2OS01ODA5KTtPT08wTzBPPCg2MjMrMzA3MC0zNjgyKTtPT08wTzBPKyspe2IrPU8wME9PT1tNYXRoLnJvdW5kKE1hdGgucmFuZG9tKCkqKDI5MTQrMTAwMy0zODU2KSldfXJldHVybihiKyJceDJkIitPT09PT08wKGEuZ2V0VGltZSgpKSl9ZnVuY3Rpb24gT08wT08oTzBPMDAwMCxPT08wTzAwKXtyZXR1cm4oZXZhbCgiXHg3NFx4NzlceDcwXHg2NVx4NmZceDY2XHgyMCIrTzBPMDAwMCsiXHgyMFx4MjFceDNkXHgyMFx4MjJceDc1XHg2ZVx4NjRceDY1XHg2Nlx4NjlceDZlXHg2NVx4NjRceDIyIik/ZXZhbChPME8wMDAwKTpPT08wTzAwKQp9ZnVuY3Rpb24gT08wTzAwMChiLGEpe3JldHVybihiKygoKGI9PSIiKXx8KChhPT0iIil8fChhLnN1YnN0cmluZygoNzYyNSsyMDM5LTk2NjQpLCg1MTg2KzQ0NzQtOTY1OSkpPT0iXHgyNiIpKSk/IiI6Ilx4MjYiKSthKX1mdW5jdGlvbiBPMDAwTzAwKCl7dmFyIGE9bmV3IERhdGUoKTtyZXR1cm4oYS5nZXRUaW1lKCkrIlx4MmUiK01hdGguZmxvb3IoTWF0aC5yYW5kb20oKSooMzgwMSsxNTczLTQzNzQpKSl9ZnVuY3Rpb24gTzAwT08oYixhKXtPT08wMFtiXT1hLnRvU3RyaW5nKCl9ZnVuY3Rpb24gTzBPTzBPMChhKXtPT08wMFthXT0iIn1mdW5jdGlvbiBPT08wMDAwKGEpe3ZhciBiPSIiLGMsZDtPTzAwT08oT08wT08oIlx4NGVceDU0XHg1MFx4NTRceDVmXHg0N1x4NGNceDQyXHg0Y1x4NDVceDU4XHg1NFx4NTJceDQxIiwiIikpO2lmKCFMbmtMY2spe09PMDBPTyhPTzBPTygiXHg0ZVx4NTRceDUwXHg1NFx4NWZceDUwXHg0N1x4NDVceDU4XHg1NFx4NTJceDQxIiwiIikpfU9PMDBPTyhhKTsKZm9yKGMgaW4gT09PMDApe2Q9T09PMDBbY107aWYodHlwZW9mKGQpPT0iXHg3M1x4NzRceDcyXHg2OVx4NmVceDY3Iil7aWYoZCYmKGQhPSIiKSl7Yj1PTzBPMDAwKGIsKGMrIlx4M2QiKyhzZWxmLmVuY29kZVVSSUNvbXBvbmVudD9lbmNvZGVVUklDb21wb25lbnQoZCk6ZXNjYXBlKGQpKSkpfX19cmV0dXJuIGJ9ZnVuY3Rpb24gTzAwMDAwMCgpe3ZhciBhO09PT09PMC5PT08wMD1uZXcgQXJyYXkoKTtmb3IoYSBpbiBPT08wMCl7T09PT08wLk9PTzAwW2FdPU9PTzAwW2FdfX1mdW5jdGlvbiBPT08wME9PKCl7dmFyIGE7T09PMDA9bmV3IEFycmF5KCk7Zm9yKGEgaW4gT09PT08wLk9PTzAwKXtPT08wMFthXT1PT09PTzAuT09PMDBbYV19fWZ1bmN0aW9uIE9PME8wT08oYixkLGMpe2lmKE9PT08wW2JdIT1udWxsKXt2YXIgYT1uZXcgRnVuY3Rpb24oZCk7T09PTzBbYl0ub25sb2FkPWE7T09PTzBbYl0ub25lcnJvcj1hO09PT08wW2JdLm9uYWJvcnQ9YX1zZXRUaW1lb3V0KGQsKGMqKDE1MjMrMzIwNi0zNzI5KSkpCn1mdW5jdGlvbiBPME8wME8wKGEsYil7aWYoYT09IiIpe3JldHVybn1PMDAwMD0oKE8wMDAwKyg0ODgyKzE0MDUtNjI4NikpJU9PT08wLmxlbmd0aCk7aWYoT09PTzBbTzAwMDBdPT1udWxsKXtPT09PMFtPMDAwMF09bmV3IEltYWdlKCg0MTAxKzQyNzYtODM3NiksKDQ2MTYrNzE1LTUzMzApKX1PT09PMFtPMDAwMF0uc3JjPWErIlx4M2YiK2J9ZnVuY3Rpb24gT09PT08wTyhiKXt2YXIgYTt2YXIgYztpZigoTzAwTzAwTyE9IiIpJiYoZG9jdW1lbnQubG9jYXRpb24ucHJvdG9jb2w9PSJceDY4XHg3NFx4NzRceDcwXHg3M1x4M2EiKSl7YT1PMDBPMDBPfWVsc2V7YT1PMDAwME9PfWM9T09PMDAwMChiKTtPME8wME8wKGEsYyk7T09PMDBPTygpfWZ1bmN0aW9uIE9PMDBPTyhiKXt2YXIgYzt2YXIgZDtpZighYil7cmV0dXJufWI9Yi50b1N0cmluZygpO2lmKGI9PSIiKXtyZXR1cm59Yz1iLnNwbGl0KCJceDI2Iik7Zm9yKGQ9KDIyMCsxMjMwLTE0NTApO2Q8Yy5sZW5ndGg7ZCsrKXt2YXIgYT1jW2RdLnNwbGl0KCJceDNkIik7CmlmKGEubGVuZ3RoPT0oMjEwOSs0MzcwLTY0NzcpKXtPMDBPTyhhWyg0NjcyKzUxMzctOTgwOSldLChzZWxmLmRlY29kZVVSSUNvbXBvbmVudD9kZWNvZGVVUklDb21wb25lbnQoYVsoMjY4NSszODE2LTY1MDApXSk6dW5lc2NhcGUoYVsoMzQ3MSsyOTc5LTY0NDkpXSkpKX19fWZ1bmN0aW9uIE8wTzBPTyhhKXtPMDBPTygiXHg2NVx4NzRceDczIixPMDAwTzAwKCkpO09PT09PME8oYSk7cmV0dXJuIHRydWV9ZnVuY3Rpb24gTzAwT08wTyhlLGEsYyl7dmFyIGI7aWYoIWV8fCFlLmhyZWYpe3JldHVybiB0cnVlfWlmKExua0xjayl7cmV0dXJuIGZhbHNlfUxua0xjaz1lO2lmKE9PMDAwLmxjKXtPMDBPTygiXHg2Y1x4NjMiLGUuaHJlZil9aWYoT08wMDAucmYpe2lmKCFPME9PMDAwfHwhdG9wfHwhdG9wLmRvY3VtZW50KXtPMDBPTygiXHg3Mlx4NjYiLGRvY3VtZW50LmxvY2F0aW9uKX19TzBPME9PKGEpO2lmKGMpe2I9Y31lbHNle2I9TlRQVF9NQVhUQUdXQUlUfWlmKGI+KDE2MjUrNjg3NC04NDk5KSl7dmFyIGQ7CmlmKGUuY2xpY2spe2UudG1wY2xjaz1lLm9uY2xpY2s7ZS5vbmNsaWNrPW51bGw7ZD0iXHg2OVx4NjZceDIwXHgyOFx4MjBceDRjXHg2ZVx4NmJceDRjXHg2M1x4NmJceDIwXHgyOVx4MjBceDdiXHgyMFx4NGNceDZlXHg2Ylx4NGNceDYzXHg2Ylx4MmVceDYzXHg2Y1x4NjlceDYzXHg2Ylx4MjhceDI5XHgzYlx4MjBceDRjXHg2ZVx4NmJceDRjXHg2M1x4NmJceDJlXHg2Zlx4NmVceDYzXHg2Y1x4NjlceDYzXHg2Ylx4MjBceDNkXHgyMFx4NGNceDZlXHg2Ylx4NGNceDYzXHg2Ylx4MmVceDc0XHg2ZFx4NzBceDYzXHg2Y1x4NjNceDZiXHgzYlx4MjBceDRjXHg2ZVx4NmJceDRjXHg2M1x4NmJceDIwXHgzZFx4MjBceDZlXHg3NVx4NmNceDZjXHgzYlx4MjBceDdkIn1lbHNle2Q9Ilx4NjlceDY2XHgyMFx4MjhceDIwXHg0Y1x4NmVceDZiXHg0Y1x4NjNceDZiXHgyMFx4MjlceDIwXHg3Ylx4MjBceDc3XHg2OVx4NmVceDY0XHg2Zlx4NzdceDJlXHg2Y1x4NmZceDYzXHg2MVx4NzRceDY5XHg2Zlx4NmVceDJlXHg2OFx4NzJceDY1XHg2Nlx4MjBceDNkXHgyMFx4MjIiK2UuaHJlZisiXHgyMlx4M2JceDIwXHg0Y1x4NmVceDZiXHg0Y1x4NjNceDZiXHgyMFx4M2RceDIwXHg2ZVx4NzVceDZjXHg2Y1x4M2JceDIwXHg3ZCIKfU9PME8wT08oTzAwMDAsZCxiKTtyZXR1cm4gZmFsc2V9TG5rTGNrPW51bGw7cmV0dXJuIHRydWV9ZnVuY3Rpb24gTzAwME9PMChjLGEsZCl7dmFyIGI7aWYoIWN8fCFjLnN1Ym1pdCl7cmV0dXJuIHRydWV9aWYoRnJtTGNrKXtyZXR1cm4gZmFsc2V9RnJtTGNrPWM7TzBPME9PKGEpO2lmKGQpe2I9ZH1lbHNle2I9TlRQVF9NQVhUQUdXQUlUfWlmKGI+KDUyNzErNDQwNi05Njc3KSl7Yy50bXBzYm10PWMub25zdWJtaXQ7Yy5vbnN1Ym1pdD1udWxsO09PME8wT08oTzAwMDAsIlx4NjlceDY2XHgyMFx4MjhceDIwXHg0Nlx4NzJceDZkXHg0Y1x4NjNceDZiXHgyMFx4MjlceDIwXHg3Ylx4MjBceDQ2XHg3Mlx4NmRceDRjXHg2M1x4NmJceDJlXHg3M1x4NzVceDYyXHg2ZFx4NjlceDc0XHgyOFx4MjlceDNiXHgyMFx4NDZceDcyXHg2ZFx4NGNceDYzXHg2Ylx4MmVceDZmXHg2ZVx4NzNceDc1XHg2Mlx4NmRceDY5XHg3NFx4MjBceDNkXHgyMFx4NDZceDcyXHg2ZFx4NGNceDYzXHg2Ylx4MmVceDc0XHg2ZFx4NzBceDczXHg2Mlx4NmRceDc0XHgzYlx4MjBceDQ2XHg3Mlx4NmRceDRjXHg2M1x4NmJceDIwXHgzZFx4MjBceDZlXHg3NVx4NmNceDZjXHgzYlx4MjBceDdkIixiKTsKcmV0dXJuIGZhbHNlfUZybUxjaz1udWxsO3JldHVybiB0cnVlfXZhciBPMDAwME9PPU5UUFRfSU1HU1JDO3ZhciBPTzAwMD1OVFBUX0ZMRFM7dmFyIE8wME9PMD1PTzBPTygiXHg0ZVx4NTRceDUwXHg1NFx4NWZceDQ3XHg0Y1x4NDJceDRjXHg0M1x4NGZceDRmXHg0Ylx4NDlceDQ1XHg1MyIsbnVsbCk7dmFyIE9PT08wTz1PTzBPTygiXHg0ZVx4NTRceDUwXHg1NFx4NWZceDUwXHg0N1x4NDNceDRmXHg0Zlx4NGJceDQ5XHg0NVx4NTMiLG51bGwpO3ZhciBPT08wME8wPU9PME9PKCJceDRlXHg1NFx4NTBceDU0XHg1Zlx4NTNceDQ1XHg1NFx4NWZceDQ5XHg0NFx4NDNceDRmXHg0Zlx4NGJceDQ5XHg0NSIsZmFsc2UpO3ZhciBPTzBPTzA9T08wT08oIlx4NGVceDU0XHg1MFx4NTRceDVmXHg0OVx4NDRceDQzXHg0Zlx4NGZceDRiXHg0OVx4NDVceDVmXHg0ZVx4NDFceDRkXHg0NSIsIlx4NTNceDYxXHg2ZVx4NjVceDQ5XHg0NCIpO3ZhciBPTzAwTzAwPU9PME9PKCJceDRlXHg1NFx4NTBceDU0XHg1Zlx4NDlceDQ0XHg0M1x4NGZceDRmXHg0Ylx4NDlceDQ1XHg1Zlx4NDRceDRmXHg0ZFx4NDFceDQ5XHg0ZSIsbnVsbCk7CnZhciBPTzBPT09PPU9PME9PKCJceDRlXHg1NFx4NTBceDU0XHg1Zlx4NDlceDQ0XHg0M1x4NGZceDRmXHg0Ylx4NDlceDQ1XHg1Zlx4NDVceDU4XHg1MFx4NDlceDUyXHg0NSIsMTU1NTIwMDAwKTt2YXIgTzAwTzAwTz1PTzBPTygiXHg0ZVx4NTRceDUwXHg1NFx4NWZceDQ4XHg1NFx4NTRceDUwXHg1M1x4NDlceDRkXHg0N1x4NTNceDUyXHg0MyIsIiIpO3ZhciBPME9PMDAwPU9PME9PKCJceDRlXHg1NFx4NTBceDU0XHg1Zlx4NTBceDQ3XHg1Mlx4NDVceDQ2XHg1NFx4NGZceDUwIixPTzBPTygiXHg0ZVx4NTRceDUwXHg1NFx4NWZceDQ3XHg0Y1x4NDJceDRjXHg1Mlx4NDVceDQ2XHg1NFx4NGZceDUwIixmYWxzZSkpO3ZhciBPTzAwMDAwPU9PME9PKCJceDRlXHg1NFx4NTBceDU0XHg1Zlx4NGVceDRmXHg0OVx4NGVceDQ5XHg1NFx4NDlceDQxXHg0Y1x4NTRceDQxXHg0NyIsZmFsc2UpO3ZhciBudHB0QWRkUGFpcj1PMDBPTzt2YXIgbnRwdERyb3BQYWlyPU8wT08wTzA7dmFyIG50cHRFdmVudFRhZz1PME8wT087CnZhciBudHB0TGlua1RhZz1PMDBPTzBPO3ZhciBudHB0U3VibWl0VGFnPU8wMDBPTzA7dmFyIE9PTzAwPW5ldyBBcnJheSgpO3ZhciBPT09PTzA9bmV3IE9iamVjdCgpO3ZhciBPT09PMD1BcnJheSgoNzkxKzM1NDAtNDMyMSkpO3ZhciBPMDAwMDtmb3IoTzAwMDA9KDU1MDgrMzU5MC05MDk4KTtPMDAwMDxPT09PMC5sZW5ndGg7TzAwMDArKyl7T09PTzBbTzAwMDBdPW51bGx9dmFyIExua0xjaz1udWxsO3ZhciBGcm1MY2s9bnVsbDtPMDBPTygiXHg2YVx4NzMiLCJceDMxIik7TzAwT08oIlx4NzRceDczIixPMDAwTzAwKCkpO2lmKE9PMDAwLmxjKXtPMDBPTygiXHg2Y1x4NjMiLGRvY3VtZW50LmxvY2F0aW9uKX1pZihPTzAwMC5yZil7dmFyIE9PTzBPTztpZihPME9PMDAwJiZ0b3AmJnRvcC5kb2N1bWVudCl7T09PME9PPXRvcC5kb2N1bWVudC5yZWZlcnJlcn1lbHNle09PTzBPTz1kb2N1bWVudC5yZWZlcnJlcn1PMDBPTygiXHg3Mlx4NjYiLE9PTzBPTyl9aWYoc2VsZi5zY3JlZW4pe2lmKE9PMDAwLnJzKXtPMDBPTygiXHg3Mlx4NzMiLHNlbGYuc2NyZWVuLndpZHRoKyJceDc4IitzZWxmLnNjcmVlbi5oZWlnaHQpCn1pZihPTzAwMC5jZCl7TzAwT08oIlx4NjNceDY0IixzZWxmLnNjcmVlbi5jb2xvckRlcHRoKX19aWYoT08wMDAubG4pe3ZhciBPT08wTztpZihuYXZpZ2F0b3IubGFuZ3VhZ2Upe09PTzBPPW5hdmlnYXRvci5sYW5ndWFnZX1lbHNle2lmKG5hdmlnYXRvci51c2VyTGFuZ3VhZ2Upe09PTzBPPW5hdmlnYXRvci51c2VyTGFuZ3VhZ2V9ZWxzZXtPT08wTz0iIn19aWYoT09PME8ubGVuZ3RoPigxMTIyKzIyMDMtMzMyMykpe09PTzBPPU9PTzBPLnN1YnN0cmluZygoMzY1MyszNTU1LTcyMDgpLCgzOTArODM5NS04NzgzKSl9T09PME89T09PME8udG9Mb3dlckNhc2UoKTtPMDBPTygiXHg2Y1x4NmUiLE9PTzBPKX1pZihPTzAwMC50eil7dmFyIE9PME8wO3ZhciBPME8wME89bmV3IERhdGUoKTt2YXIgTzBPMDA9TzBPMDBPLmdldFRpbWV6b25lT2Zmc2V0KCk7dmFyIE8wT08wMDtPTzBPMD0iXHg0N1x4NGRceDU0IjtpZihPME8wMCE9KDQ2MjgrNDM0OC04OTc2KSl7aWYoTzBPMDA+KDE5MDcrNjc3Mi04Njc5KSl7T08wTzArPSJceDIwXHgyZCIKfWVsc2V7T08wTzArPSJceDIwXHgyYiJ9TzBPMDA9TWF0aC5hYnMoTzBPMDApO08wT08wMD1NYXRoLmZsb29yKE8wTzAwLygyMTY4KzMzOTEtNTQ5OSkpO08wTzAwLT1PME9PMDAqKDMxMzErNDA0Ni03MTE3KTtpZihPME9PMDA8KDUwOTQrOTY5LTYwNTMpKXtPTzBPMCs9Ilx4MzAifU9PME8wKz1PME9PMDArIlx4M2EiO2lmKE8wTzAwPCgyOTc3KzIwOC0zMTc1KSl7T08wTzArPSJceDMwIn1PTzBPMCs9TzBPMDB9TzAwT08oIlx4NzRceDdhIixPTzBPMCl9aWYoT08wMDAuanYpe3ZhciBPMDAwME87aWYobmF2aWdhdG9yLmphdmFFbmFibGVkKCkpe08wMDAwTz0iXHgzMSJ9ZWxzZXtPMDAwME89Ilx4MzAifU8wME9PKCJceDZhXHg3NiIsTzAwMDBPKX12YXIgTzBPTzA9bmV3IEFycmF5KCk7dmFyIE8wME8wT089ZmFsc2U7aWYoT08wMDAuY2spe3ZhciBPME8wTzA7dmFyIE8wME8wLE8wT09PMDtpZihPMDBPTzApe2ZvcihPME8wTzA9KDIxNzArNzMwNi05NDc2KTtPME8wTzA8TzAwT08wLmxlbmd0aDsKTzBPME8wKyspe08wT08wW08wME9PMFtPME8wTzBdXT0iIn19aWYoT09PTzBPKXtmb3IoTzBPME8wPSg2OTU0KzkzMS03ODg1KTtPME8wTzA8T09PTzBPLmxlbmd0aDtPME8wTzArKyl7TzBPTzBbT09PTzBPW08wTzBPMF1dPSIifX1mb3IoT08wME8gaW4gTzBPTzApe08wME8wPU9PT08wMChPTzAwTyk7aWYoTzAwTzApe08wT08wW09PMDBPXT1PMDBPMH19aWYoT09PMDBPMCl7TzAwTzA9T09PTzAwKE9PME9PMCk7aWYoTzAwTzApe08wT08wW09PME9PMF09TzAwTzA7TzAwTzBPTz10cnVlfX1PME9PTzA9TzAwMDAwTyhPME9PMCk7aWYoTzBPT08wIT0iIil7TzAwT08oIlx4NjNceDZiIixPME9PTzApfX1PMDAwMDAwKCk7aWYoIU9PMDAwMDApe09PT09PME8oIiIpfWlmKE9PTzAwTzAmJiFPMDBPME9PKXt2YXIgTzAwTzA9T09PTzAwKE9PME9PMCk7aWYoIU8wME8wKXtPMDBPMD1PME8wMDBPKCk7T09PTzAwMChPTzBPTzAsTzAwTzAsT08wT09PTyxPTzAwTzAwKTtpZihPTzAwMC5jayYmT09PTzAwKE9PME9PMCkpe08wT08wW09PME9PMF09TzAwTzA7CnZhciBPME9PTzA9TzAwMDAwTyhPME9PMCk7aWYoTzBPT08wIT0iIil7TzAwT08oIlx4NjNceDZiIixPME9PTzApO08wMDAwMDAoKX19fX12YXIgXzB4ODBiZT1bIlx4NjZceDc1XHg2RVx4NjNceDc0XHg2OVx4NkZceDZFIiwiXHg2Mlx4NkZceDY0XHg3OSIsIlx4NjFceDY0XHg2NFx4NDVceDc2XHg2NVx4NkVceDc0XHg0Q1x4NjlceDczXHg3NFx4NjVceDZFXHg2NVx4NzIiLCJceDYxXHg3NFx4NzRceDYxXHg2M1x4NjhceDQ1XHg3Nlx4NjVceDZFXHg3NCIsIlx4NkZceDZFIiwiXHg0RFx4NTNceDQ5XHg0NSIsIlx4NjlceDZFXHg2NFx4NjVceDc4XHg0Rlx4NjYiLCJceDYxXHg3MFx4NzBceDU2XHg2NVx4NzJceDczXHg2OVx4NkZceDZFIiwiXHg2M1x4NkNceDY5XHg2M1x4NkIiLCJceDZEXHg2Rlx4NzVceDczXHg2NVx4NjRceDZGXHg3N1x4NkUiLCJceDcwXHg2MVx4NzJceDYxXHg2RFx4NzMiLCJceDZDXHg2NVx4NkVceDY3XHg3NFx4NjgiLCJceDczXHg2NVx4NjFceDcyXHg2M1x4NjgiLCJceDczXHg3NVx4NjJceDczXHg3NFx4NzJceDY5XHg2RVx4NjciLCJceDIwIiwiXHg3Mlx4NjVceDcwXHg2Q1x4NjFceDYzXHg2NSIsIlx4MjYiLCJceDczXHg3MFx4NkNceDY5XHg3NCIsIlx4M0QiLCJceDY3XHg2NVx4NzQiLCJceDcwXHg3Mlx4NkZceDc0XHg2Rlx4NzRceDc5XHg3MFx4NjUiLCJceDYzXHg2Rlx4NkVceDc0XHg2MVx4NjlceDZFXHg3MyIsIlx4NzRceDZGXHg0Q1x4NkZceDc3XHg2NVx4NzJceDQzXHg2MVx4NzNceDY1IiwiXHg2OFx4NkZceDczXHg3NFx4NkVceDYxXHg2RFx4NjUiLCJceDZDXHg2Rlx4NjNceDYxXHg3NFx4NjlceDZGXHg2RSIsIlx4MkMiLCIiLCJceDJFIiwiXHg2Q1x4NjFceDczXHg3NFx4NDlceDZFXHg2NFx4NjVceDc4XHg0Rlx4NjYiLCJceDc0XHg2MVx4NzJceDY3XHg2NVx4NzQiLCJceDczXHg3Mlx4NjNceDQ1XHg2Q1x4NjVceDZEXHg2NVx4NkVceDc0IiwiXHg3MFx4NjFceDcyXHg2NVx4NkVceDc0XHg0NVx4NkNceDY1XHg2RFx4NjVceDZFXHg3NCIsIlx4NzBceDYxXHg3Mlx4NjVceDZFXHg3NFx4NEVceDZGXHg2NFx4NjUiLCJceDc0XHg2MVx4NjdceDRFXHg2MVx4NkRceDY1IiwiXHg2NVx4NzZceDY1XHg2RVx4NzQiLCJceDc3XHg2OFx4NjlceDYzXHg2OCIsIlx4NkVceDc1XHg2RFx4NjJceDY1XHg3MiIsIlx4NDEiLCJceDY4XHg3Mlx4NjVceDY2IiwiXHgzQSIsIlx4M0YiLCJceDYxXHg3NFx4NzRceDYxXHg2M1x4NjhceDZEXHg2NVx4NkVceDc0IiwiXHg0Nlx4NDlceDRDXHg0NSIsIlx4NjFceDc0XHg3NFx4NjFceDYzXHg2OFx4NkRceDY1XHg2RVx4NzRceDRFXHg2MVx4NkRceDY1IiwiXHg2RVx4NkZceDZFXHg2NSIsIlx4NzBceDYxXHg3NFx4NjhceDZFXHg2MVx4NkRceDY1IiwiXHgyRiIsIlx4NzBceDcyXHg2Rlx4NzRceDZGXHg2M1x4NkZceDZDIiwiXHg2MVx4NkNceDZDIiwiXHg2OVx4NkVceDZFXHg2NVx4NzJceDU0XHg2NVx4NzhceDc0IiwiXHg3NFx4NjVceDc4XHg3NCIsIlx4NDlceDREXHg0NyIsIlx4NjFceDZDXHg3NCIsIlx4NjlceDZFXHg2RVx4NjVceDcyXHg0OFx4NTRceDREXHg0QyIsIlx4NjZceDc0XHg3MFx4M0EiLCJceDczXHg3NVx4NjJceDczXHg3NFx4NzIiLCJceDY5XHg2Mlx4NkRceDQ1XHg3Nlx4NDFceDYzXHg3NFx4NjlceDZGXHg2RVx4M0QiLCJceDI2XHg2NVx4NzZceDNEXHg2NFx4NkZceDc3XHg2RVx4NkNceDZGXHg2MVx4NjQiLCJceDY4XHg3NFx4NzRceDcwIiwiXHg2RFx4NjFceDY5XHg2Q1x4NzRceDZGIiwiXHg2NVx4NzZceDNEXHg2NVx4NzhceDc0XHg2NVx4NzJceDZFXHg2MVx4NkNceDIwXHg2Q1x4NjlceDZFXHg2Qlx4MjZceDY5XHg2Mlx4NkRceDQ1XHg3Nlx4NDFceDYzXHg3NFx4NjlceDZGXHg2RVx4M0QiLCJceDYyXHg3NVx4NzRceDc0XHg2Rlx4NkUiLCJceDUzXHg2MVx4NjZceDYxXHg3Mlx4NjkiLCJceDc1XHg3M1x4NjVceDcyXHg0MVx4NjdceDY1XHg2RVx4NzQiLCJceDc1XHg2RVx4NjRceDY1XHg2Nlx4NjlceDZFXHg2NVx4NjQiXTsKdmFyIGV2aG5kbHI9dHJ1ZTtmdW5jdGlvbiBwYXVzZShjKXt2YXIgYj1uZXcgRGF0ZSgpO3ZhciBhPW51bGw7ZG97YT1uZXcgRGF0ZSgpfXdoaWxlKGEtYjxjKX1mdW5jdGlvbiB0dXJuX2VoX29mZigpe2V2aG5kbHI9ZmFsc2V9ZnVuY3Rpb24gYmluZF9ldmVudChiLGEpe2lmKCh0eXBlb2YoYSk9PSJmdW5jdGlvbiIpJiZkb2N1bWVudC5ib2R5KXtpZihkb2N1bWVudC5ib2R5LmFkZEV2ZW50TGlzdGVuZXIpe2RvY3VtZW50LmJvZHkuYWRkRXZlbnRMaXN0ZW5lcihiLGEsdHJ1ZSl9ZWxzZXtpZihkb2N1bWVudC5ib2R5LmF0dGFjaEV2ZW50KXtkb2N1bWVudC5ib2R5LmF0dGFjaEV2ZW50KCJvbiIrYixhKX19fX1mdW5jdGlvbiBldmVudF90cmFja2luZygpe3ZhciBhPShuYXZpZ2F0b3IuYXBwVmVyc2lvbi5pbmRleE9mKCJDaHJvbWUiKXx8bmF2aWdhdG9yLmFwcFZlcnNpb24uaW5kZXhPZigiTVNJRSIpIT0tMSk/ImNsaWNrIjoibW91c2Vkb3duIjtiaW5kX2V2ZW50KGEsZG93bmxvYWRfdHJhY2tpbmcpOwpiaW5kX2V2ZW50KGEsb2Zmc2l0ZV90cmFja2luZyk7YT0obmF2aWdhdG9yLmFwcFZlcnNpb24uaW5kZXhPZigiQ2hyb21lIil8fG5hdmlnYXRvci5hcHBWZXJzaW9uLmluZGV4T2YoIk1TSUUiKSE9LTEpPyJjb250ZXh0bWVudSI6Im1vdXNlZG93biI7YmluZF9ldmVudChhLHJpZ2h0X2NsaWNrX3RyYWNraW5nKX1mdW5jdGlvbiBRdWVyeXN0cmluZyhhKXt0aGlzLnBhcmFtcz17fTtpZihhPT1udWxsKXthPWxvY2F0aW9uLnNlYXJjaC5zdWJzdHJpbmcoMSxsb2NhdGlvbi5zZWFyY2gubGVuZ3RoKX1pZihhLmxlbmd0aD09MCl7cmV0dXJufWE9YS5yZXBsYWNlKC9cKy9nLCIgIik7dmFyIGM9YS5zcGxpdCgiJiIpO2Zvcih2YXIgZD0wO2Q8Yy5sZW5ndGg7ZCsrKXt2YXIgZj1jW2RdLnNwbGl0KCI9Iik7dmFyIGI9ZGVjb2RlVVJJQ29tcG9uZW50KGZbMF0pO3ZhciBlPShmLmxlbmd0aD09Mik/ZGVjb2RlVVJJQ29tcG9uZW50KGZbMV0pOmI7dGhpcy5wYXJhbXNbYl09ZX19UXVlcnlzdHJpbmcucHJvdG90eXBlLmdldD1mdW5jdGlvbihhLGIpe3ZhciBjPXRoaXMucGFyYW1zW2FdOwpyZXR1cm4oYyE9bnVsbCk/YzpifTtRdWVyeXN0cmluZy5wcm90b3R5cGUuY29udGFpbnM9ZnVuY3Rpb24oYSl7dmFyIGI9dGhpcy5wYXJhbXNbYV07cmV0dXJuKGIhPW51bGwpfTtmdW5jdGlvbiBkb210ZXN0KGMpe2lmKGMubGVuZ3RoPjApe2M9Yy50b0xvd2VyQ2FzZSgpO2lmKGM9PXdpbmRvdy5sb2NhdGlvbi5ob3N0bmFtZS50b0xvd2VyQ2FzZSgpKXtyZXR1cm4gdHJ1ZX1lbHNle3ZhciBkPXZhcmxpc3QoTlRQVF9ET01BSU5MSVNUKTt2YXIgYT1kLmxlbmd0aDtmb3IodmFyIGI9MDtiPGE7YisrKXtpZihjPT1kW2JdfHxjLnNlYXJjaChkW2JdKSE9LTEpe3JldHVybiB0cnVlfX19fXJldHVybiBmYWxzZX1mdW5jdGlvbiB2YXJsaXN0KGQpe3ZhciBiPWQudG9Mb3dlckNhc2UoKS5zcGxpdCgiLCIpO3ZhciBhPWIubGVuZ3RoO2Zvcih2YXIgYz0wO2M8YTtjKyspe2JbY109YltjXS5yZXBsYWNlKC9eXHMqLywiIikucmVwbGFjZSgvXHMqJC8sIiIpfXJldHVybiBifWZ1bmN0aW9uIG1hdGNoKGYsZSl7dmFyIGQ9Zi5zdWJzdHJpbmcoZi5sYXN0SW5kZXhPZigiLiIpKzEsZi5sZW5ndGgpOwp2YXIgYz12YXJsaXN0KGUpO3ZhciBiPWMubGVuZ3RoO2Zvcih2YXIgYT0wO2E8YjthKyspe2lmKGQ9PWNbYV0pe3JldHVybiB0cnVlfX1yZXR1cm4gZmFsc2V9ZnVuY3Rpb24gZXZ0X2VsZW1lbnQoYixhKXt2YXIgZD1iLnRhcmdldHx8Yi5zcmNFbGVtZW50O3doaWxlKGQudGFnTmFtZSYmKGQudGFnTmFtZS50b0xvd2VyQ2FzZSgpIT1hLnRvTG93ZXJDYXNlKCkpKXt2YXIgYz1kLnBhcmVudEVsZW1lbnR8fGQucGFyZW50Tm9kZTtpZighYyl7cmV0dXJuIGR9ZD1jfXJldHVybiBkfWZ1bmN0aW9uIGRvd25sb2FkX3RyYWNraW5nKGope2o9anx8KHdpbmRvdy5ldmVudHx8IiIpO2lmKGomJigodHlwZW9mKGoud2hpY2gpIT0ibnVtYmVyIil8fChqLndoaWNoPT0xKSkpe3ZhciBxPWV2dF9lbGVtZW50KGosIkEiKTtpZihxLmhyZWYpe3ZhciBhPXEuaG9zdG5hbWU/KHEuaG9zdG5hbWUuc3BsaXQoIjoiKVswXSk6IiI7dmFyIG49ZXNjYXBlKHEuaHJlZik7dmFyIG09cS5zZWFyY2g/cS5zZWFyY2guc3Vic3RyaW5nKHEuc2VhcmNoLmluZGV4T2YoIj8iKSsxLHEuc2VhcmNoLmxlbmd0aCk6IiI7CnZhciBrPW5ldyBRdWVyeXN0cmluZyhtKTt2YXIgZD1rLmdldCgiYXR0YWNobWVudCIpO3ZhciBjPWsuZ2V0KCJGSUxFIik7dmFyIGI9ay5nZXQoImF0dGFjaG1lbnROYW1lIik7aWYoZD09bnVsbCYmYz09bnVsbCYmYj09bnVsbCl7dmFyIG89Im5vbmUifWVsc2V7aWYoZD09bnVsbCYmYz09bnVsbCl7dmFyIG89Yn1lbHNle2lmKGQ9PW51bGwpe3ZhciBvPWN9ZWxzZXt2YXIgbz1kfX19dmFyIHA9by50b0xvd2VyQ2FzZSgpO3ZhciBnPXEucGF0aG5hbWUudG9Mb3dlckNhc2UoKTtpZihkb210ZXN0KGEpJiYobWF0Y2goZyxOVFBUX0RPV05MT0FEVFlQRVMpfHxtYXRjaChwLE5UUFRfRE9XTkxPQURUWVBFUykpKXt2YXIgZj1xLnBhdGhuYW1lPygocS5wYXRobmFtZS5pbmRleE9mKCIvIikhPTApPyIvIitxLnBhdGhuYW1lOnEucGF0aG5hbWUpOiIvIjt2YXIgbD1xLnByb3RvY29sO3ZhciBoPSIiO3ZhciBpPWRvY3VtZW50LmFsbD9xLmlubmVyVGV4dDpxLnRleHQ7dmFyIHM9ZXZ0X2VsZW1lbnQoaiwiSU1HIik7CmlmKHMuYWx0KXtoPXMuYWx0fWVsc2V7aWYoaSl7aD1pfWVsc2V7aWYocS5pbm5lckhUTUwpe2g9cS5pbm5lckhUTUx9fX1pZihxLnByb3RvY29sPT0iZnRwOiIpe3ZhciByPW4uc3Vic3RyKDgpfWVsc2V7dmFyIHI9bi5zdWJzdHIoOSl9aWYoZXZobmRsciE9ZmFsc2Upe2lmKG89PSJub25lIil7bnRwdEV2ZW50VGFnKCJpYm1FdkFjdGlvbj0iK3IudG9Mb3dlckNhc2UoKSsiJmV2PWRvd25sb2FkIik7cGF1c2UoNTAwKX1lbHNle250cHRFdmVudFRhZygiaWJtRXZBY3Rpb249IitwKyImZXY9ZG93bmxvYWQiKTtwYXVzZSg1MDApfX19fX19ZnVuY3Rpb24gb2Zmc2l0ZV90cmFja2luZyhhKXthPWF8fCh3aW5kb3cuZXZlbnR8fCIiKTtpZihhJiYoKHR5cGVvZihhLndoaWNoKSE9Im51bWJlciIpfHwoYS53aGljaD09MSkpKXt2YXIgZj1ldnRfZWxlbWVudChhLCJBIik7aWYoZi5ocmVmKXt2YXIgaD1mLmhvc3RuYW1lPyhmLmhvc3RuYW1lLnNwbGl0KCI6IilbMF0pOiIiO3ZhciBpPWYucHJvdG9jb2x8fCIiOwppZigoaC5sZW5ndGg+MCkmJihpLmluZGV4T2YoImh0dHAiKT09MHx8aS5pbmRleE9mKCJtYWlsdG8iKT09MCkmJighZG9tdGVzdChoKSkpe3ZhciBkPWYuc2VhcmNoP2Yuc2VhcmNoLnN1YnN0cmluZyhmLnNlYXJjaC5pbmRleE9mKCI/IikrMSxmLnNlYXJjaC5sZW5ndGgpOiIiO3ZhciBnPWYucGF0aG5hbWU/KChmLnBhdGhuYW1lLmluZGV4T2YoIi8iKSE9MCk/Ii8iK2YucGF0aG5hbWU6Zi5wYXRobmFtZSk6Ii8iO3ZhciBjPWVzY2FwZShmLmhyZWYpO3ZhciBiPWMuc3Vic3RyKDkpO2lmKGV2aG5kbHIhPWZhbHNlKXtudHB0RXZlbnRUYWcoImV2PWV4dGVybmFsIGxpbmsmaWJtRXZBY3Rpb249IitiKTtwYXVzZSg1MDApfX19fX1mdW5jdGlvbiByaWdodF9jbGlja190cmFja2luZyhxKXtxPXF8fCh3aW5kb3cuZXZlbnR8fCIiKTtpZihxKXt2YXIgYz1xLndoaWNofHxxLmJ1dHRvbjtpZigoYyE9MSl8fChuYXZpZ2F0b3IudXNlckFnZW50LmluZGV4T2YoIlNhZmFyaSIpIT0tMSkpe3ZhciBrPWV2dF9lbGVtZW50KHEsIkEiKTsKaWYoKHR5cGVvZihrLmhyZWYpIT0idW5kZWZpbmVkIikmJmsuaHJlZil7aWYoKHR5cGVvZihrLnByb3RvY29sKSE9InVuZGVmaW5lZCIpJiZrLnByb3RvY29sKXt2YXIgbD1rLnNlYXJjaD9rLnNlYXJjaC5zdWJzdHJpbmcoay5zZWFyY2guaW5kZXhPZigiPyIpKzEsay5zZWFyY2gubGVuZ3RoKToiIjt2YXIgaT1uZXcgUXVlcnlzdHJpbmcobCk7dmFyIHA9aS5nZXQoImF0dGFjaG1lbnQiKTt2YXIgbz1pLmdldCgiRklMRSIpO3ZhciBuPWkuZ2V0KCJhdHRhY2htZW50TmFtZSIpO2lmKHA9PW51bGwmJm89PW51bGwmJm49PW51bGwpe3ZhciBoPSJub25lIn1lbHNle2lmKHA9PW51bGwmJm89PW51bGwpe3ZhciBoPW59ZWxzZXtpZihwPT1udWxsKXt2YXIgaD1vfWVsc2V7dmFyIGg9cH19fXZhciBnPWgudG9Mb3dlckNhc2UoKTt2YXIgZD1rLnBhdGhuYW1lLnRvTG93ZXJDYXNlKCk7aWYoKHR5cGVvZihrLnBhdGhuYW1lKSE9InVuZGVmaW5lZCIpJiYobWF0Y2goZCxOVFBUX0RPV05MT0FEVFlQRVMpfHxtYXRjaChnLE5UUFRfRE9XTkxPQURUWVBFUykpKXt2YXIgaj1rLnBhdGhuYW1lPygoay5wYXRobmFtZS5pbmRleE9mKCIvIikhPTApPyIvIitrLnBhdGhuYW1lOmsucGF0aG5hbWUpOiIvIjsKdmFyIGE9ay5ob3N0bmFtZT8oay5ob3N0bmFtZS5zcGxpdCgiOiIpWzBdKToiIjt2YXIgbT1lc2NhcGUoay5ocmVmKTtpZihrLnByb3RvY29sPT0iZnRwOiIpe3ZhciBmPW0uc3Vic3RyKDgpfWVsc2V7dmFyIGY9bS5zdWJzdHIoOSl9aWYoZXZobmRsciE9ZmFsc2Upe2lmKGg9PSJub25lIil7bnRwdEV2ZW50VGFnKCJpYm1FdkFjdGlvbj0iK2YudG9Mb3dlckNhc2UoKSsiJmV2PWRvd25sb2FkIik7cmV0dXJufWVsc2V7bnRwdEV2ZW50VGFnKCJpYm1FdkFjdGlvbj0iK2crIiZldj1kb3dubG9hZCIpO3JldHVybn19fX1pZihrLmhyZWYpe3ZhciBhPWsuaG9zdG5hbWU/KGsuaG9zdG5hbWUuc3BsaXQoIjoiKVswXSk6IiI7dmFyIGI9ay5wcm90b2NvbHx8IiI7aWYoKGEubGVuZ3RoPjApJiYoYi5pbmRleE9mKCJodHRwIik9PTB8fGIuaW5kZXhPZigibWFpbHRvIik9PTApJiYoIWRvbXRlc3QoYSkpKXt2YXIgbD1rLnNlYXJjaD9rLnNlYXJjaC5zdWJzdHJpbmcoay5zZWFyY2guaW5kZXhPZigiPyIpKzEsay5zZWFyY2gubGVuZ3RoKToiIjsKdmFyIGo9ay5wYXRobmFtZT8oKGsucGF0aG5hbWUuaW5kZXhPZigiLyIpIT0wKT8iLyIray5wYXRobmFtZTprLnBhdGhuYW1lKToiLyI7dmFyIG09ZXNjYXBlKGsuaHJlZik7dmFyIGY9bS5zdWJzdHIoOSk7aWYoZXZobmRsciE9ZmFsc2Upe250cHRFdmVudFRhZygiZXY9ZXh0ZXJuYWwgbGluayZpYm1FdkFjdGlvbj0iK2YpfX19fX19fWV2ZW50X3RyYWNraW5nKCk7KGZ1bmN0aW9uKCl7dmFyIGI9e307dmFyIGE9ZG9jdW1lbnQuZ2V0RWxlbWVudHNCeVRhZ05hbWUoIm1ldGEiKTtmb3IodmFyIGQ9MCxjPWEubGVuZ3RoO2Q8YztkKyspe2lmKCEhYVtkXS5uYW1lKXtiW2FbZF0ubmFtZS50b0xvd2VyQ2FzZSgpXT1hW2RdLmNvbnRlbnR9fXZhciBlPWZ1bmN0aW9uKGcpe2c9Zy50b0xvd2VyQ2FzZSgpO2lmKCEhYltnXSl7cmV0dXJuIGJbZ119cmV0dXJuIG51bGx9O3ZhciBmPWZ1bmN0aW9uKGcpe3ZhciBoPWUoZyk7aWY